### ISSUE TITLE
您好，是否可以支持CogVLM等多模态模型？

### ISSUE THREAD

**Issue by jacks-tang** [GraphPKU/PiSSA#15]

**Comment by fxmeng** [comment]
我们目前除了LLM中的线性层，还支持了卷积层和embedding层。有了这些模块，多模态模型也可以用上PiSSA。我们将会初始化并分享相应初始化的checkpoint，敬请期待。

**Comment by jacks-tang** [comment]
期待您分享一个用PiSSA在多模态模型(如CogVLM、InternVL等)微调的案例
