### ISSUE TITLE
如何使用CodeFeedBack数据集进行微调的？

### ISSUE THREAD

**Issue by Peroplex** [GraphPKU/PiSSA#17]
PiSSA论文里有提到使用CodeFeedBack数据集进行微调测试human-eval和mbpp数据集，但是我在项目里没有看到相关内容，想知道贵团队是如何对codefeedback数据集进行预处理微调训练的

**Comment by fxmeng** [comment]
我们使用的训练数据可以从这里获得：
https://huggingface.co/collections/fxmeng/pissa-datasets-661ce700721235e542a5d7a8
测试代码基于这个项目：
https://github.com/evalplus/evalplus
