### ISSUE TITLE
您好，PiSSA是否可以与LoRAMoE等方法进行结合，作为LoRA的初始化？LoRAMoE: Alleviate World Knowledge Forgetting in Large Language Models via MoE-Style Plugin

### ISSUE THREAD

**Issue by Shubao-Zhao** [GraphPKU/PiSSA#21]

**Comment by fxmeng** [comment]
抱歉回复的有点晚，
LoRA的各种改进方法，都可以尝试和PiSSA进行结合。不过为了合理性和创新性，需要针对性的修改。
例如PiSSA和LoRAMoE结合，由于所有的adapter并不是全部被激活，所以直接把模型分解到不同的adapter里，初始时并不等价于原模型。
一种改进方法是，只用奇异值分解后的奇异向量，将奇异值取0，然后在训练过程中逐渐的学习每个方向的更新。
不过pissa/lora的一个好处是可以合并进原始模型，不增加推理成本，moe里的 router会导致无法合并，尽管效果好，实际推理速度会慢一些，这个问题需要解决一下。
