### ISSUE TITLE
Where is the evaluation code?

### ISSUE THREAD

**Issue by Ther-nullptr** [GraphPKU/PiSSA#22]
Hello, you say evaluation code is there, but I found nothing:-(
https://huggingface.co/datasets/fxmeng/pissa-evaluation-code

**Comment by Gunale0926** [comment]
Same question here.

**Comment by MyToumaKazusa** [comment]
Try this: https://github.com/iboing/CorDA/tree/main
better method, same evaluation, detailed guidance

**Comment by fxmeng** [comment]
The evaluation dataset and corresponding code have been prepared:
```
cd PiSSA/
git lfs install
git clone https://huggingface.co/datasets/fxmeng/pissa-dataset
python gen_vllm.py --model $OUTPUT_PATH --sub_task gsm8k math python  --output_file $OUTPUT_PATH/all_response.jsonl
python test_acc.py --input_file $OUTPUT_PATH/all_response.jsonl 
python pissa-dataset/python_process_preds.py --path $OUTPUT_PATH/all_response.jsonl
evalplus.evaluate --dataset humaneval --samples $OUTPUT_PATH/humaneval.jsonl 
evalplus.evaluate --dataset mbpp --samples $OUTPUT_PATH/mbpp.jsonl 
```

**Comment by gapsong** [comment]
@fxmeng where is the evaluation code for the NLU tasks?

<img width="918" height="373" alt="Image" src="https://github.com/user-attachments/assets/fa7fa8cf-267c-481b-9935-e07a2a4f42fa" />
