### ISSUE TITLE
fast svd

### ISSUE THREAD

**Issue by hhnqqq** [GraphPKU/PiSSA#25]
我在peft里面似乎没有找到快速svd的代码
这是我自己用的代码，不知道是否和论文里的一致
```python
            V, S, Uh = randomized_svd(self.weight.data.numpy(), n_components=self.lora_rank, random_state=None)
            Vr, Sr, Ur = map(torch.from_numpy, (V, S, Uh))
```

**Comment by hhnqqq** [comment]
另外，论文里的 Table 4: Comparation between SVD and Fast SVD in terms of initialization time, error and training loss有点看不懂

**Comment by hhnqqq** [comment]
我懂了，设置n_iters的话就是fast svd

**Comment by fxmeng** [comment]
快速svd的代码在这里：https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/layer.py#L253-L258
