### ISSUE TITLE
Loss Landscape

### ISSUE THREAD

**Issue by yaya-sy** [GraphPKU/PiSSA#28]
Hi,  

Thank you for your work and for sharing the code! Is it possible for you to share the code you used to generate the loss landscape figures?  

Thank you!

**Comment by fxmeng** [comment]
The code for plotting the loss landscape is available in [this folder](https://github.com/GraphPKU/PiSSA/tree/main/loss_landscape). Simply run the following command:

```
cd PiSSA/loss_landscape
python main.py
```
