### ISSUE TITLE
reproduce the results 

### ISSUE THREAD

**Issue by lucasliunju** [GraphPKU/PiSSA#4]
Thanks for your great work.

I would like to ask whether we can use this codebase to reproduce the results about lora anf full fine-tuning. The main reason is that I would like to fairly comapre the performance between pissa, lora anf full fine-tuning.

Best

**Comment by fxmeng** [comment]
Thank you for your interest in PiSSA. 
It takes some time to clean up the codes and training scripts, which are now available at: 
https://github.com/GraphPKU/PiSSA/tree/main/scripts. You can use different scripts from this directory according to your needs.

**Comment by lucasliunju** [comment]
Thank you very much for your answer and great work!
