### ISSUE TITLE
Unable to unzip the MetaMathQA-395K.json.zip

### ISSUE THREAD

**Issue by poaboagye** [GraphPKU/PiSSA#5]
Hi. Congrats on this work. I want to reproduce the results in your paper, but I cannot unzip the MetaMathQA-395K.json.zip file. Could you help me out? Thank you!

I tried using:
git lfs install 
git lfs pull

**Comment by fxmeng** [comment]
Due to file size limitations, the previous compressed file was corrupted during upload. However, all three datasets are publicly accessible and can be found here: https://huggingface.co/collections/fxmeng/pissa-661ce700721235e542a5d7a8

**Comment by poaboagye** [comment]
Thank you. I will download it from there.
